### ISSUE TITLE
the render function don't need to return the jsx expression?

### ISSUE THREAD

**Issue by beenotung** [mistlog/svelte-draft-template#1]
https://github.com/mistlog/svelte-draft-template/blob/c3362f93bff7798db9b5b4f4326af23ebbe91bf1/src/component/Link.tsx#L11

**Comment by mistlog** [comment]
> https://github.com/mistlog/svelte-draft-template/blob/c3362f93bff7798db9b5b4f4326af23ebbe91bf1/src/component/Link.tsx#L11

Yes, just like what we do in svelte, you just "declare" what you want to render. 

The render function is not real function and it will never be called, what happens underhood is that we will collect all jsx and group them together, see implementation here:

> https://github.com/mistlog/svelte-draft/blob/master/src/section/template-section.tsx#L7

Thus it's even possible to write jsx seperately and use props "on demand", see example in unit test file:

> https://github.com/mistlog/svelte-draft/blob/master/test/section/script-section.test.ts#L100

Meanwhile, the file is end with ".tsx", however, we write it in [typedraft](https://github.com/mistlog/typedraft), the difference is that we write code "in context", as it's clear that we want to render jsx, we don't need to rely on return statement to express this intention.

I'm sorry that currently the document is not complete, the plan is to implement svelte-draft completly and refactor all examples in [svelte tutorial](https://svelte.dev/tutorial/basics), then the docs will be added with references to these examples.

Please feel free to ask any questions before the document is added.

**Comment by beenotung** [comment]
the "on demand" approach looks good and safe

**Comment by mistlog** [comment]
> the "on demand" approach looks good and safe

Yes, it works fine if there is no root element, however, if there is a root element, we have to write jsx as a whole, possible solution may be https://github.com/mistlog/svelte-draft-todo-mvc/issues/1#issuecomment-581120586.

**Comment by mistlog** [comment]
Now it's documented, maybe we can close this issue.
link: https://github.com/mistlog/svelte-draft-docs/blob/master/introduction/introduction.md#adding-data
